# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4408058dffa2398096813830d18a24f88bad407291e8e7b1215413cc490b7d42b446ec37e0ba2908a496d9196f456204f350bb18419cefa85c3b550b29b831e2

test:
  secret_key_base: 67a25ec4d6def55bff5df216df27bc3aea2125ee9c1a7371a2a49678ac81a653ceb0d1da6ded8900e33a2b154fb34e6b8bcbc87317acb9875b1724decc1d00ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
